Gemfile
spec/spec_helper.rb

I find these to be useful for developing and reviewing pull requests, but if there is any drawback to adding these, then let's not do it.

Add SimpleCov & Pry as development dependencies

---

README.md
spec/configuration_spec.rb

This class was previously implicitly tested through `spec/pdfkit_spec.rb`
Also, updated documentation to reflect what our code really does when detecting the wkhtmltopdf command.

Add tests for PDFKit::Configuration

---

lib/pdfkit/pdfkit.rb
spec/pdfkit_spec.rb

other PR which references this problem breaks headers and footers. This simple change stops cover and toc from being prepended with -- when the options are normalized.

cover and toc should not be prepended with -- when passed as options

---

spec/pdfkit_spec.rb
spec/source_spec.rb

- Add tests for initialization
- Change `context` blocks to `describe`
- Fix assorted typos
- Also whitespace in spec/source_spec.rb.

Add tests for PDFKit::PDFKit#new

---

lib/pdfkit/middleware.rb
spec/middleware_spec.rb

Previously if there was a tag with href='/' followed by another tag with a relative URL, the contents of the second tag would not be replaced with an absolute URL. Added a test for this edge case and tweaked the regexp to fix.
The second commit moves the caching flag into the initialize method so it's only set once. It was being deleted from the conditions instance var on the first run, then set to false for all subsequent runs.

Ensure regexp correctly matches relative root path and move caching flag

---

lib/pdfkit/pdfkit.rb
spec/pdfkit_spec.rb

This PR fixes a bug related to the handling on string values for repeatable options. 
Previous functionality:
```
$ pdfkit = PDFKit.new('html', allow: "http://google.com")
$ pdfkit.options.include?(['--allow', 'http://google.com'])
=> false
```
New functionality:
```
$ pdfkit = PDFKit.new('html', allow: "http://google.com")
$ pdfkit.options[['--allow', 'http://google.com']]
=> ''
$ pdfkit = PDFKit.new('html', allow: {"http://google.com" => nil, "http://myapp.com" => nil)
$ pdfkit.options[['--allow', 'http://google.com']]
=> ''
```
I believe this is the correct functionality.

Fix bug with repeating keys with string values

---

lib/pdfkit/pdfkit.rb
spec/pdfkit_spec.rb

Windows command escaping is rather different and alas, can't rely on shelljoin . It doesn't look like there's anything in stdlib to handle it either, hence the implementation inlined herein.

make command escaping work on windows

---

spec/middleware_spec.rb
spec/pdfkit_spec.rb
spec/source_spec.rb

This addresses two issues:
- removes the one instance of Rspec `should` that was causing a warning to appear every time we rant eh test suite
- makes our test naming conventions consistent by removing "should" from the beginning of many tests

Remove should from test suite

---

lib/pdfkit/pdfkit.rb
lib/pdfkit/source.rb
spec/pdfkit_spec.rb
spec/source_spec.rb

Fixes #166
Current Functionality (master):
```
>> PDFKit.new('https://www.google.com/search?q=pdfkit').command
wkhtmltopdf ... https://www.google.com/search\\?q\\=pdfkit
```
New Functionality (this PR):
```
>> PDFKit.new('https://www.google.com/search?q=pdfkit').command
wkhtmltopdf ... https://www.google.com/search?q=pdfkit
```
To accomplish this, this PR walks back some security measures implemented in #164.
* We no longer escape URLs
* We no longer escape HTML coming through middleware.
I don't know enough about bash exploits, so forgive the poor examples below.
This would impact those using PDFKit who allow raw user input in the URL (e.g. `www.mysite.com/echo /etc/passwd`) or in the HTML (e.g. `"<p>Your PDF Content: echo /etc/passwd</p>"` ).
On the other hand, I think we need to …

Do not shellescape URLs since it borks params 

---

CHANGELOG.md

@pdfkit/rb Releasing 0.8.1 tomorrow with the following changes:
- Fix shell escaping issues for Windows (thanks muness)
- Fix shell escaping issues for URLs, introduced in 0.5.3 release

Bump to 0.8.1

---

README.md
lib/pdfkit.rb
lib/pdfkit/html_preprocessor.rb
lib/pdfkit/middleware.rb
lib/pdfkit/pdfkit.rb
spec/html_preprocessor_spec.rb
spec/middleware_spec.rb

@sigmavirus24 Here's a working solution for what I was proposing in #343.
To an end-user, the only effect is that the `:root_url` (and the `:protocol`) options now can be passed right to the PDFKit constructor. Configuring `root_url` still works, too.
This PR introduces `PDFKit::HtmlPreprocessor`, which could maybe also handle inserting the `<stylesheet>` tags, but I didn't want to change too much at once.
What do you think?

Honor `root_url` in core

---

lib/pdfkit/middleware.rb

This code is being used in every request to the application. So it should work as fast as possible.
What's done:
1. `end_with?` vs. `match(regexp)`
```ruby
require 'benchmark/ips'
u = 'http://www.pdf995.com/samples/pdf.pdf'
Benchmark.ips do |x|
x.report('match')     { u.match %r[\.pdf$] }
x.report('end_with?') { u.end_with? '.pdf' }
x.compare!
end
```
2. `Array()` vs. `[].flatten`
```ruby
require 'benchmark/ips'
conditions = %w[a long time ago in a galaxy far far away]
Benchmark.ips do |x|
x.report('[].flatten') { [conditions].flatten }
x.report('Array()')    { Array(conditions) }
x.compare!
end
```
3. Immediately return `false` in `render_as_pdf?` method if the path doesn't end with `.pdf`.
4. String interpolation is faster than concatenation.

Minor optimizations in middleware

---

pdfkit.gemspec

This information will appear on the gem's page on rubygems.org.
http://guides.rubygems.org/specification-reference/#requirements

Add gemspec requirements attribute

---

lib/pdfkit/middleware.rb
spec/middleware_spec.rb

This change allows the page to respond with a dynamically calculated javascript delay option through the header
The code could be made pretty generic if the desire to pass other options back through was needed?

Allow PDFKit middleware to receive javascript delay option

---

lib/pdfkit/configuration.rb
lib/pdfkit/pdfkit.rb
spec/configuration_spec.rb
spec/pdfkit_spec.rb

Introduces `xvfb` config option, which is false by default.
It changes executable to run in a `xvfb-run` wrapper.
/cc @sigmavirus24

Xvfb support

---

README.md

Fixes #385.
This was added in error, as part of #344, in 2febadcd028d51e73d8187745c54dabefd2597d2.
The `PDFKit` constructor _does_ support a `protocol` option, but `PDFKit::Configuration` doesn't.

Remove `config.protocol` from the README.

---

lib/pdfkit/middleware.rb
spec/middleware_spec.rb

Fixes #358.
The commits are maybe not in the best order for the long-term history - they're ordered to illuminate the problem we found, and the solution we made, in the order they came up. I hope this helps make the chain of thought clearer, and the PR easier. (Feel free to check out any particular commit, and run the specs to get a better feel for what's going on.) I'm happy to rebase however you'd like, before the final merge.
I had to upgrade .ruby-version to at least 2.2.2, because rack won't install for less than that:
```
ERROR:  Error installing rack:
rack requires Ruby version >= 2.2.2.
```
I updated only to 2.2.2, so as to make minimal changes, and get me on my way. I'll leave the question of whether to upgrade, and to which version, to the PDFKit team: let me know, and I'll …

Make PDFkit threadsafe

---

README.md
lib/pdfkit/middleware.rb
spec/middleware_spec.rb

Enable to configure the disposition on middleware.
It Allow to force download and define a filename on middleware.
This PR fixes the issue #371

Option to force download in Middleware

---

lib/pdfkit/configuration.rb
spec/configuration_spec.rb

The implemented fix comes from the suggestion in #376 but I think the following fix is better: 
```diff
diff --git a/lib/pdfkit/pdfkit.rb b/lib/pdfkit/pdfkit.rb
index e8f79be..2edb883 100644
--- a/lib/pdfkit/pdfkit.rb
+++ b/lib/pdfkit/pdfkit.rb
@@ -24,7 +24,7 @@ class PDFKit
@stylesheets = []
options = PDFKit.configuration.default_options.merge(options)
-    options.delete(:quiet) if PDFKit.configuration.verbose?
+    options[:quiet] = !PDFKit.configuration.verbose? unless options.include?(:quiet)
options.merge! find_options_in_meta(url_file_or_html) unless source.url?
@root_url = options.delete(:root_url)
@protocol = options.delete(:protocol)
```
Thoughts?

Don't break verbose when assigning default options [fixes #376]

---

README.md
lib/pdfkit/middleware.rb
spec/middleware_spec.rb

#437 added the ability to specify disposition at the middleware level.
However, this had the unexpected side-effect of steamrolling any per-request disposition headers currently set, which was a pretty massive change in behaviour in a patch release.
This updates the logic to only set the Content Disposition header if it doesn't already exist.

Don't override request level Content-Disposition header if it exists

---

lib/pdfkit/pdfkit.rb
lib/pdfkit/source.rb

When pdfkit is used in an rspec test run using the rspec binary, the
tests pass even with the missing require for tempfile, because rspec
is bringing in tempfile.  But running pdfkit outside of a test
environment, in a project that is not already bringing in tempfile,
will fail.
The test for this is:
```
#!/usr/bin/env ruby
require "pdfkit"
PDFKit.new("")
```
Which results in a stack trace including:
```
/home/wayne/.rvm/gems/ruby-2.7.1/gems/pdfkit-0.8.4.2/lib/pdfkit/pdfkit.rb:94:in `find_options_in_meta': uninitialized constant PDFKit::Tempfile (NameError)
```
I don't know how to make a good test for this in rspec, since rspec hides the problem by bringing in the missing library.  I guess the test could shell out to a little test file like the one above, but I don't know if that's worth …

Add missing require statements for tempfile

---

lib/pdfkit/configuration.rb
spec/configuration_spec.rb

When running pdfkit in a docker container for our configuration, there is no home directory. Bundler < 2 has a warning for this and it goes to STDOUT (see: https://github.com/rubygems/bundler/issues/6067). Here is the example:
```ruby
irb(main):001:0> `bundle exec which wkhtmltopdf`.chomp
=> "`/home/myuser` is not a directory.\nBundler will use `/tmp/bundler/home/myuser' as your home directory temporarily.\n/usr/bin/wkhtmltopdf"
irb(main):002:0> `bundle exec which wkhtmltopdf`.chomp.lines.last
=> "/usr/bin/wkhtmltopdf"
```
Now an example where the warning does not come up:
```ruby
2.4.6 :001 > `bundle exec which wkhtmltopdf`.chomp
=> "/usr/local/bin/wkhtmltopdf"
2.4.6 :002 > `bundle exec which wkhtmltopdf`.chomp.lines.last
=> "/usr/local/bin/wkhtmltopdf"
```
This PR seems to be very …

Only grab last line of bundle exec which output

---

lib/pdfkit/middleware.rb
spec/middleware_spec.rb

If an error occurs in the middleware we should reflect that in the response status instead of echoing the success of the unmodified response.
This will help with response status test assertions. We recently had middleware misconfiguration issues which were not caught by tests expecting a 200 response.

Return 500 status when an exception is caught in middleware

---

.travis.yml
Gemfile
README.md
lib/pdfkit/pdfkit.rb
pdfkit.gemspec
spec/pdfkit_spec.rb

In Rails 6, the spec of `ActiveSupport::SafeBuffer` methods has been changed.
Previously, it behaves like just String, but now `ActiveSupport::SafeBuffer` exactly.
See for details: https://github.com/rails/rails/pull/33990
This change breaks stylesheets rendering.
The rendered PDF has too escaped style tag.
There is a result of failing spec that I added in 760a8edbaa0534aaf4dd02b718ea17dc2671c157.
``` console
$ RAILS_VERSION="~> 6.0.0" bundle exec rspec spec/pdfkit_spec.rb:504
Run options: include {:locations=>{"./spec/pdfkit_spec.rb"=>[504]}}
F
Failures:
1) PDFKit#to_pdf can deal with ActiveSupport::SafeBuffer if the HTML doesn't have a head tag
Failure/Error: expect(pdfkit.source.to_s).to include("<style>#{File.read(css)}</style>")
expected "&lt;style&gt;body { font-size: 20px; …
```

Fix to render stylesheets as html safe string on Rails 6

---

.github/workflows/test.yml

Migrate from TravisCI to Github Actions. Please note that the wkhtmltopdf binary had been updated to the latest `0.12.6-1` in the test workflow.

Enable tests on GitHub Actions

---

lib/pdfkit/source.rb
spec/source_spec.rb

In my opinion, the [CVE-2022-25765](https://www.cve.org/CVERecord?id=CVE-2022-25765) issue was caused by partially escaped URLs. They need to be escaped.
```ruby
def url_needs_escaping?
URI::DEFAULT_PARSER.unescape(@source) == @source ||
URI::DEFAULT_PARSER.escape(URI::DEFAULT_PARSER.unescape(@source)) != @source
end
```
We add an additional condition for method `url_needs_escaping?` for checking url was a partially escaped URLs or not, by escaped it after unescaped . If the result not matched to source it should be escaped again.

Partially escaped URLs should be escaped

---

lib/pdfkit/middleware.rb
spec/middleware_spec.rb

The changes in #511 change what headers get set by PDFKit and make all headers set by PDFKit lower-case.
However, the changes also affect code depending on headers set by the app - which for Rack 2.x apps will be 'Content-Type'.
To address this, the code should check if `Content-Type` is present and in that case use it, otherwise default to content-type.
As the code also sets this header (changing the content type to `'application/pdf'`), it should set the same header that the original value is retrieved from.
So decide on the exact header name first, store it in the `content_type_header` variable, and use it to index the headers dict.
Fix #515.

fix: support non-lower-case Content-Type header provided by app

---

lib/pdfkit/configuration.rb
lib/pdfkit/pdfkit.rb
lib/pdfkit/source.rb
lib/pdfkit/wkhtmltopdf.rb
spec/pdfkit_spec.rb
spec/source_spec.rb
spec/spec_helper.rb

I hope this is a simpler solution to #518 as it avoids complex shell-escaping/input-sanitizing logic in favor of calling `IO.popen` with an Array of separate command arguments.
* By calling `IO.popen` with an Array of command arguments (ex: `['ls', '-l', ...]`) it runs the command as a separate process instead of running it in a sub-shell as a shell command. This prevents any arbitrary command injection, without needing complex shell-escaping logic. https://ruby-doc.org/core-3.1.2/IO.html#method-c-popen
* Changed `Configuration#executable` to return a String or an Array for when xvfb mode is enabled.
* Changed `PDFKit#command` to return an Array of command arguments for `IO.popen`.
* Removed argument quoting logic as it's not necessary when calling `IO.popen` with an Array of arguments.
* …

Call `IO.popen` with an Array of command arguments (#518).

---

lib/pdfkit/pdfkit.rb
spec/pdfkit_spec.rb

I got the below error when passing `Pathname` object to `PDFKit#to_file` in PDFKit v0.8.7.2.
```
TypeError:
no implicit conversion of Pathname into String
```
I think this error introduced in v0.8.7.2(#519).

Allow passing a `Pathname` object to the `path` argument

---

.github/workflows/test.yml
spec/pdfkit_spec.rb

Hey there!
The bump to v0.8.7.3 in #529 looks like it was failing due to a couple of issues:
- The `ruby/setup-ruby@v1` action, when running with Ruby 2.5, cannot use the most recent `rubygem-updater`
- Some specs involving complex key examples were using `--replace`, to validate it could parse `wkhtmltopdf` options that handle multiple options, that started to fail with the changes in #523  
This PR updates the specs to use `header-left`, which also [takes complex keys](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/6a57c1449797d6cb915921fb747f3ac36199241f/docs/usage/wkhtmltopdf.txt#LL292C15-L292C15), which I think should be a reasonable replacement for that spec. Open to other alternatives though!
I've also made a somewhat janky update to the `test.yml` Github action runner, which will …

V0.8.7.3 build failure fixes
